Adding Milano Gravel 5.0 tracks
BikeRoutes/BikeRoutes pull request #18
Opened 2020-12-02 19:03 UTC by ecamellini

Adding tracks from here: https://www.turbolento.net/milano-gravel-5-0/

2020-12-02 19:06 UTC, ecamellini commented
Volendo qua ce ne sono un bel po' di tracce da provare, intanto iniziamo con queste :) 
https://www.turbolento.net/le-strade-zitte-new-2/

2020-12-05 20:23 UTC, dhinus requested changes
Ci sta aggiungere queste tracce, però faccio il rompicazzo:

* teniamo i Readme in inglese (gli altri sono in inglese, se no viene un paciocco con metà in inglese e metà in italiano)
* ripuliamo un po' i filename dei geojson
* proporrei di rinominare le cartelle con "Turbolento - nome route" in modo che siano facilmente identificabili quelle che abbiamo preso da loro

2020-12-07 14:31 UTC, ecamellini commented
@dhinus done 💛

2020-12-07 18:43 UTC, dhinus approved these changes

2020-12-07 18:43 UTC, merged