Industrial archaeology
BikeRoutes/BikeRoutes pull request #7
Opened 2020-05-17 17:13 UTC by FrancescoCioria

2020-05-18 20:54 UTC, dhinus commented on Italy/Lombardia/Archeologia Industriale/README.md
> +We'll also go across a small street full of street art in the NoLo neighborhood, all by cutting through small and big parks.
❤️

2020-05-18 21:01 UTC, dhinus requested changes
Molto bello!

Sistemerei solo tre punticini:

<img width="351" alt="Screenshot 2020-05-18 at 22 58 13" src="https://user-images.githubusercontent.com/474311/82259173-6f80b100-995b-11ea-9ed4-ae881c40ca4c.png">

<img width="367" alt="Screenshot 2020-05-18 at 22 58 26" src="https://user-images.githubusercontent.com/474311/82258996-27fa2500-995b-11ea-8a8e-36c980593a1d.png">

<img width="320" alt="Screenshot 2020-05-18 at 22 57 48" src="https://user-images.githubusercontent.com/474311/82259208-790a1900-995b-11ea-8549-bcbf2bc77977.png">

2020-05-19 08:29 UTC, dhinus approved these changes

2020-05-19 08:29 UTC, dhinus commented
Se hai voglia, ultime due cosine, altrimenti fai pure merge così:

<img width="87" alt="Screenshot 2020-05-19 at 10 29 40" src="https://user-images.githubusercontent.com/474311/82303732-aab2cc80-99bb-11ea-8dda-fb8ab0234484.png">


<img width="615" alt="Screenshot 2020-05-19 at 10 27 50" src="https://user-images.githubusercontent.com/474311/82303706-9d95dd80-99bb-11ea-92c1-2f18d0ca2636.png">

2020-05-19 09:30 UTC, ecamellini commented
❤️ 🏗️

2020-05-19 09:30 UTC, ecamellini approved these changes

2020-05-19 09:55 UTC, merged